### ISSUE TITLE
%player_name% / {playerName} doesn't work

### ISSUE THREAD

**Issue by Xferno2** [ProjectG-Plugins/GeyserHub#20]
As said in the title the plugin doesn't replace the player name, I tried both the default %player_name% and the {playerName} which is wrote in the wiki pages. The same behavior is seen both in Java and Bedrock Edition.

Here is the config part:
![image](https://user-images.githubusercontent.com/25592644/135729853-0ba94575-15a7-4a0e-8529-057de76eeaa1.png)
And the console log that shows the mv tp command cannot be executed because instead of calling my name it calls %player_name%
![image](https://user-images.githubusercontent.com/25592644/135729857-61a71d56-f6bf-43a3-b22c-52771a00541f.png)
Yes I'm using the plugin to change world rather than the server itself.
These are the plugins on my server:
![image](https://user-images.githubusercontent.com/25592644/135730152-5ccdf57a-4cc2-47fc-a857-9acb8f220343.png)
ChatReplacer and XfernoBundle are made by me but even if disabled the behavior is the same.

This is the full config: [Pastebin](https://pastebin.com/qV4C6P3z)

The plugin was downloaded from the spigot link, other than that everything else works.

**Comment by Konicai** [comment]
Hi, unfortunately the wiki is outdated. If PlaceholderAPI isn't installed, %player_name% and %player_uuid% will be translated by us. If PlaceholderAPI is installed, you'll need to make sure you have the Player extension https://api.extendedclip.com/expansions/player/

**Comment by Xferno2** [comment]
Thank you very much, that fixed it. I installed the player expansion.
I will close this issue but before I do that, I might suggest a world blacklist. For example I would still be able to use /ghub from that world but I would no longer get the server selector item in my inventory or entirely disable the plugin for that world, no /ghub, no server selector.
Keep up the good work!

**Comment by Konicai** [comment]
Thanks, unfortunately haven't had much time recently. I'll make a feature request for it
