### ISSUE TITLE
YAW/PITCH for hub join/spawn TP

### ISSUE THREAD

**Issue by Tydium** [ProjectG-Plugins/GeyserHub#22]
When players join it would be nice to set where their player is facing. Perhaps you can add it in as config options (well duh haha)

**Comment by Jens-Co** [comment]
Can you try to change the world spawn location command, since we use bukkit/bungeecord default server transfer I assume it uses the default loc. That command will apply player placement loc.

**Comment by Konicai** [comment]
Join teleporter is formatted like this
https://github.com/ProjectG-Plugins/GeyserHub/blob/master/src/main/resources/config.yml#L13-L16

I might just replace both join mesages and join teleporter with a list of commands to run

**Comment by Tydium** [comment]
When setting the world border it doesn't set the rotation of the body or anything. I tried this with bot Multiverse + /setworldspawn
