### ISSUE TITLE
/gteleporter command does not work on bedrock clients

### ISSUE THREAD

**Issue by ghost** [ProjectG-Plugins/GeyserHub#27]
Hello, 
I installed the plugin on my server and tried to use the command /gteleporter . On Java, it says that it is only a bedrock command. But if I  use it on Bedrock, it says the same. Do I have to configure something in the configs or is this a bug?

**Comment by Konicai** [comment]
You're likely running Geyser on a proxy and don't have floodgate on the backend server properly configured. Read the floodgate docs again or join the Geyser Discord
